# -*- coding: utf-8 -*-
"""Despliegue_Proyecto_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qz6bFOIo7u5AinxeBAUHl07t6bikno6b

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'  # Archivo del modelo Random Forest
modelo = pickle.load(open(filename, 'rb'))
modelo

#Cargamos los datos futuros
#data = pd.read_csv("datos_futuros.csv")
#data.head()

#INTERFAZ GRAFICA
#Se crea interfaz gráfica con streamlit para captura de los datos


import pandas as pd

st.title('Estimar anticipadamente cuántas personas que diligencian el formulario terminarán pagando')

Edad = st.slider('Edad', min_value=18, max_value=70, value=20, step=1)
Genero = st.selectbox('Genero', ['M', 'F'])
Naturaleza_Origen_Universidad= st.selectbox('Naturaleza Origen Universidad', ['Publica', 'Privada','Otro'])
Tipo_Documento= st.selectbox('Tipo Documento', ['CC', 'CE','PA','DE','TI'])
Programa=st.selectbox('Programa',['Esp en Psiquiatria-Med', 'Esp Medicina Interna-Med', 'Esp Med Dol y Cui Pal-Med', 'Esp Dermatologia-Med', 'Esp Radiologia e Imag Diag-Med', 'Esp en Oftalmologia-Med', 'Esp Ortopedia y Traumatol-Med', 'Especializac. Anestesiolog-Med', 'Esp Ginecolo y Obstetricia-Med', 'Esp Cirugia General-Med', 'Esp en Pediatria-Med', 'Esp Med Critic Cuid Intens-Med', 'Esp Med Critic Cuid Intens-Med', 'Esp en Cardiologia Adultos-Med', 'Esp. Med Activ Fis y Depor-Med', 'Esp Medicina Materno Fetal-Med', 'Esp Cirugia Cardiovascular-Med', 'Esp. En Reumatologia-Med', 'Esp en Endocrinologia-Med', 'Esp. en Neonatologia-Med', 'Esp en Infectologia-Med', 'Esp Anestesia Cardiovascul-Med', 'Esp en Nefrologia-Med', 'Esp en Ecocardiografia-Med', 'Esp Cardiol Interv y Hemod-Med', 'Esp Cardiologia Pediatrica-Med', 'Esp.Psiquiatria de Enlace-Med', 'Esp.Ortop y Traumat Pediat-Med', 'Esp. en Cirugia de Mano-Med'])
#Dataframe
datos = [[Edad, Genero, Naturaleza_Origen_Universidad, Tipo_Documento, Programa]]
data = pd.DataFrame(datos, columns=['Edad', 'Genero','Naturaleza Origen Universidad','Tipo Documento','Programa Admision'])

# Añadir columnas faltantes con valores por defecto y asegurar el orden
data['Periodo'] = 202401 # Valor por defecto
data['Presentan examen'] = 0 # Valor por defecto
data['Pais Nacimiento'] = 'Colombia' # Valor por defecto o el más frecuente del entrenamiento
data['Departamento Nacimiento'] = 'Bogota D.C.' # Valor por defecto
data['Ciudad Residencia'] = 'Bogota D.C.' # Valor por defecto

# Reordenar las columnas de 'data' según el orden esperado por el modelo (model_features original)
# Aunque model_features contiene los nombres originales, es un buen punto de partida para el orden
# y para identificar todas las columnas base necesarias antes de la codificación one-hot.
# Asumimos que model_features (modelo[2]) son las columnas iniciales antes de get_dummies
model_features_original = modelo[2]
data = data[model_features_original]
data.head()

#Se realiza la preparación de datos
data_preparada=data.copy()

# Eliminar la columna 'Prediccion' si existe, ya que no es una característica de entrada
if 'Prediccion' in data_preparada.columns:
    data_preparada = data_preparada.drop(columns=['Prediccion'])

# Definir todas las columnas categóricas que deben ser one-hot encoded
categorical_cols_for_dummies = [
    'Periodo', # Se añade Periodo para One-Hot Encoding
    'Programa Admision', 'Genero', 'Pais Nacimiento', 'Tipo Documento',
    'Departamento Nacimiento', 'Ciudad Residencia', 'Naturaleza Origen Universidad'
]

# Aplicar one-hot encoding a todas las columnas categóricas
data_preparada = pd.get_dummies(data_preparada, columns=categorical_cols_for_dummies, drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes y se alinean
# Obtener los nombres de las características esperadas por el modelo entrenado
# Se asume que el modelo (modelo[0]) tiene el atributo feature_names_in_ disponible.
expected_feature_names = modelo[0].feature_names_in_
data_preparada = data_preparada.reindex(columns=expected_feature_names, fill_value=0)
data_preparada.head()

#Hacemos la predicción con el Random Forest
Y_pred = modelo[0].predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Celda de codigo con adverntencia de error

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 1% (mape: error porcentual)")